// todo shouldn't be all constants SCREAMING_SNAKE_CASE

export const tags = [
  // styles
  'wrestling',
  'gi-only',

  // positions
  'closed-guard',
  'open-guard',
  'half-guard',
  'mount',
  'side-control',
  'back-control',
  'north-south',
  'knee-on-belly',
  'turtle',
  'spider-guard',
  'de-la-riva',
  'x-guard',
  'butterfly-guard',
  'reverse-de-la-riva',
  'lasso-guard',
  '50-50-guard',
  'z-guard',
  'rubber-guard',
  'inverted-guard',
  'combat-base',
  // submissions
  'armbar',
  'triangle',
  'kimura',
  'omoplata',
  'americana',
  'ezekiel',
  'rear-naked-choke',
  'guillotine',
  'anaconda',
  'd-arce',
  'bow-and-arrow',
  'cross-collar-choke',
  'arm-triangle',
  'wristlock',
  'heel-hook',
  'kneebar',
  'toe-hold',
  'calf-slicer',
  'gogoplata',
  'loop-choke',
  // actions
  'grip-fighting',
  'frame',
  'shrimp',
  'bridge',
  'granby-roll',
  'leg-drag',
  'back-step',
  'sprawl',
  'arm-drag',
  'hip-bump',
  'scissor',
  'flower-sweep',
  'pendulum',
  // concepts
  'pressure',
  'base',
  'balance',
  'leverage',
  'weight-distribution',
  'posture',
  'connection',
  'timing',
  'angle',
  'distance-control',
  'leg-locks',
  'wrist-ride',
  'heel-hook-defense',
  'speed-passing',
  'grip-stripping',
  // passes
  'toreando-pass',
  'knee-slice',
  'over-under-pass',
  'stack-pass',
  'smash-pass',
  'x-pass',
  'leg-weave',
  'floating-pass',
  // techniques
  'berimbolo',
  'kiss-of-the-dragon',
  'matrix',
  'electric-chair',
  'bolo',
  'worm-guard',
  'lapeloplata',
  'tarikoplata',
  'dead-orchard',
  'crab-ride',
  'honey-hole',
  // additional
  'lapel-chokes',
  'belt-chokes',
  'turtle-attacks',
  'straight-ankle-lock',
  'saddle',
  'estima-lock',
];
